apiVersion: apps/v1
kind: Deployment
metadata:
  name: page3
  labels:
    app: page3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: page3
  template:
    metadata:
      labels:
        app: page3
    spec:
      containers:
      - name: page3
        image: page3:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
